### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by SunHongyang10** [graphdeco-inria/hierarchical-3d-gaussians#1]
Hello~ Wonderful Work!

I am trying to run the train_coarse.py, then I meet an error:

![image](https://github.com/user-attachments/assets/1f59b49b-511f-4220-b177-7a8159740351)

I tried to solve it, but I failed😭

Is there a problem with my virtual environment?

**Comment by Vilour** [comment]
Same error here. Have you solved it?

**Comment by Snosixtyboo** [comment]
Hi,

unfortunately, this error is not super specific, we have seen it before in 3D Gaussian Splatting. We tried our best to replicate it, but we were never able to get it on any of our machines, so we never worked out how to debug it...

Could you let us know your OS / GPU (how many GPUs are in your machine)? Getting the latest NVIDIA drivers might help, but bottom line, without full access to a setup where it happens, it might be really tough to find it.

**Comment by Vilour** [comment]
> Hi,
> 
> unfortunately, this error is not super specific, we have seen it before in 3D Gaussian Splatting. We tried our best to replicate it, but we were never able to get it on any of our machines, so we never worked out how to debug it...
> 
> Could you let us know your OS / GPU (how many GPUs are in your machine)? Getting the latest NVIDIA drivers might help, but bottom line, without full access to a setup where it happens, it might be really tough to find it.

Hi,

I'm working with Ubuntu 18.04 with one GPU (RTX 3090). I used this setup in 3D Gaussian Splatting before and it works fine. By the way, my `nvcc -V` returns 11.6 and I created the virtual environment as the repo describes. Does it associate with CUDA version? Is visibility_filter really working here? Maybe I can just comment this line..

**Comment by Vilour** [comment]
The error persisted even if I comment this line..

**Comment by ameuleman** [comment]
Hi, 
Did you install pytorch corresponding to cuda 11.x?
pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu118

**Comment by Vilour** [comment]
> Hi, Did you install pytorch corresponding to cuda 11.x? pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu118

Yes, I installed pytorch with this command. By the way, the error on my machine appeared at 10040 iterations, not from the beginning.

**Comment by Vilour** [comment]
Hi,

I tied on another machine (Ubuntu 20.04/A6000) with the same dataset, and the error appears again on the 10040 iterations. I guess this issue associates with dataset?

**Comment by ameuleman** [comment]
I just tried downloading [SmallCity](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/full_scenes/small_city.zip) and running `full_train.py`. The coarse optimization went smoothly. Are we working with the same dataset?

**Comment by Vilour** [comment]
> I just tried downloading [SmallCity](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/full_scenes/small_city.zip) and running `full_train.py`. The coarse optimization went smoothly. Are we working with the same dataset?

I was working with a dataset which I collected myself. I'm trying with SmallCity right now.

**Comment by Vilour** [comment]
> I just tried downloading [SmallCity](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/full_scenes/small_city.zip) and running `full_train.py`. The coarse optimization went smoothly. Are we working with the same dataset?

I just tried with [SmallCity](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/full_scenes/small_city.zip) and the error appeared immediately.

**Comment by Snosixtyboo** [comment]
@Vilour @SunHongyang10 When it fails, could you try keep an eye on the GPU memory consumption? Is it possible that the system goes out of video memory? This should not happen on a 3090...

**Comment by SunHongyang10** [comment]
> @Vilour @SunHongyang10 When it fails, could you try keep an eye on the GPU memory consumption? Is it possible that the system goes out of video memory? This should not happen on a 3090...

I just tried with small_city dataset, and it fails immediately, my device is a 3090

**Comment by anchun** [comment]
Same here in Ubuntu20.04, with the following call stacks:

  File "train_coarse.py", line 190, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_coarse.py", line 106, in training
    loss.backward()
  File "/home/anchun/software/miniconda3/envs/hierarchical_3d_gaussians/lib/python3.12/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/home/anchun/software/miniconda3/envs/hierarchical_3d_gaussians/lib/python3.12/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/home/anchun/software/miniconda3/envs/hierarchical_3d_gaussians/lib/python3.12/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by Vilour** [comment]
> @Vilour @SunHongyang10 When it fails, could you try keep an eye on the GPU memory consumption? Is it possible that the system goes out of video memory? This should not happen on a 3090...

The video memory consumption is ok. Only takes a few gigabytes.

**Comment by ameuleman** [comment]
Hi,

Could you please provide cuda and nvidia driver versions?

**Comment by PLUS-WAVE** [comment]
> Hi,
> 
> Could you please provide cuda and nvidia driver versions?

I have same issue, here is my version:

- 3070 Laptop
- Driver Version: 560.70
- cuda 12.1

**Comment by Vilour** [comment]
> Hi,
> 
> Could you please provide cuda and nvidia driver versions?

The driver version is 525.105.17, and `torch.version.cuda` returns 11.8

**Comment by ameuleman** [comment]
Thanks for providing details. I managed to replicate the error using [nvidia/cuda:12.1.0-devel-ubuntu20.04](https://hub.docker.com/layers/nvidia/cuda/12.1.0-devel-ubuntu20.04/images/sha256-be8115ae63d27c13e93d0daf0e809b2bdc13c9c8bc4530d4365c8a44e9fb4d93). We will look into it.

**Comment by han-xiangyu** [comment]
Hi,

I met the same problem and I'm running it on a RTX 6000 Ada and ubuntu 24.04 with cuda 11.8

The error mesage is:

`$ python scripts/full_train.py --project_dir dataset/example_dataset/

creating output dir: dataset/example_dataset/output
Optimizing dataset/example_dataset/output/scaffold
Output folder: dataset/example_dataset/output/scaffold [23/07 01:21:16]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [23/07 01:21:16]
Reading camera 1158/1158 [23/07 01:21:17]
0 test images [23/07 01:21:17]
1158 train images [23/07 01:21:17]
Making Training Dataset [23/07 01:21:17]
Making Test Dataset [23/07 01:21:17]
Number of points at initialisation :  329992 [23/07 01:21:17]
Training progress:   0%|                                                                            | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/xiangyu/Projects/hierarchical-3d-gaussians/train_coarse.py", line 190, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/xiangyu/Projects/hierarchical-3d-gaussians/train_coarse.py", line 110, in training
    gaussians.max_radii2D[visibility_filter] = torch.max(gaussians.max_radii2D[visibility_filter], radii)
                                                         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%|                                                                            | 0/30000 [00:00<?, ?it/s]
Error executing train_coarse: Command 'python train_coarse.py -s dataset/example_dataset/camera_calibration/aligned --save_iterations -1 -i ../rectified/images --skybox_num 100000 --model_path dataset/example_dataset/output/scaffold --alpha_masks ../rectified/masks ' returned non-zero exit status 1.`

**Comment by ameuleman** [comment]
Hi,
We are still working on a fix. In the meantime, I ran it without issue with Ubuntu 22.04 and CUDA 12.5.  
Here is the corresponding Dockerfile:
```
FROM nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04
ARG USER_ID=1000
ARG GROUP_ID=1000
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends git wget unzip bzip2 sudo build-essential ca-certificates openssh-server vim ffmpeg libsm6 libxext6 python3-opencv gcc-11 g++-11 cmake

# conda
ENV PATH /opt/conda/bin:$PATH 
RUN wget --quiet \
    https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm -rf /tmp/*

# Create the user
RUN addgroup --gid $GROUP_ID user
RUN useradd --create-home -s /bin/bash --uid $USER_ID --gid $GROUP_ID docker
RUN adduser docker sudo
RUN echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER docker

# Setup hierarchical_3d_gaussians
RUN /opt/conda/bin/python -m ensurepip
RUN /opt/conda/bin/python -m pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
RUN /opt/conda/bin/python -m pip install plyfile tqdm joblib exif scikit-learn timm==0.4.5 opencv-python==4.9.0.80 gradio_imageslider gradio==4.29.0 matplotlib
```

With 125.Dockerfile in `hierarchical-3d-gaussians/`:
```
DATASET_DIR=<Path to dataset>
docker build -t hierarchical_3d_gaussians125 -f 125.Dockerfile .
docker run -it --gpus=all --rm -v ${PWD}:/host -v ${DATASET_DIR}:/data --network=host --ipc=host hierarchical_3d_gaussians125 /bin/sh -c "cd /host; bash"
rm -r submodules/hierarchy-rasterizer/build submodules/simple-knn/build submodules/gaussianhierarchy/build
cd submodules/gaussianhierarchy
cmake . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build -j --config Release
cd ../..
/opt/conda/bin/python scripts/full_train.py --project_dir /data
```

**Comment by Snosixtyboo** [comment]
There seems to be an issue associated with CUB, which is failing to compute the sum over a CUDA array, for no obvious reason. We are checking what can be done.

**Comment by Snosixtyboo** [comment]
There seem to be unspecified PyTorch/CUB compatibility issues on Ubuntu, we will try to figure out where they come from or if we can get a more robust alternative. In the meantime, if you can, combining PyTorch built for CUDA 12.1 with a CUDA Toolkit 12.5 installation (yes, this should be fine, minor version mismatches are allowed) seems like a good choice on Ubuntu, according to Docker.

**Comment by Linkersem** [comment]
Hi, I built docker (based on my graphics driver, I modified it appropriately) based on the provided dockerfile to run the code, and this is my dockerfile 
```
FROM nvcr.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
ARG USER_ID=1000
ARG GROUP_ID=1000
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends git wget unzip bzip2 sudo build-essential ca-certificates openssh-server vim ffmpeg libsm6 libxext6 python3-opencv gcc-11 g++-11 cmake

# conda
ENV PATH /opt/conda/bin:$PATH 
RUN wget --quiet \
    https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm -rf /tmp/*

# Create the user
RUN addgroup --gid $GROUP_ID user
RUN useradd --create-home -s /bin/bash --uid $USER_ID --gid $GROUP_ID docker
RUN adduser docker sudo
RUN echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# USER docker

# Setup hierarchical_3d_gaussians
RUN /opt/conda/bin/python -m ensurepip
RUN /opt/conda/bin/python -m pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
RUN /opt/conda/bin/python -m pip install plyfile tqdm joblib exif scikit-learn timm==0.4.5 opencv-python==4.9.0.80 gradio_imageslider gradio==4.29.0 matplotlib
```
but it keeps getting stuck here
![image](https://github.com/user-attachments/assets/4cf3c198-9578-4612-9ce7-5a0d85ed1a27)

**Comment by Linkersem** [comment]
> Hi, I built docker (based on my graphics driver, I modified it appropriately) based on the provided dockerfile to run the code, and this is my dockerfile
> 
> ```
> FROM nvcr.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
> ARG USER_ID=1000
> ARG GROUP_ID=1000
> ENV DEBIAN_FRONTEND=noninteractive
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends git wget unzip bzip2 sudo build-essential ca-certificates openssh-server vim ffmpeg libsm6 libxext6 python3-opencv gcc-11 g++-11 cmake
> 
> # conda
> ENV PATH /opt/conda/bin:$PATH 
> RUN wget --quiet \
>     https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
>     echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
>     /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
>     rm -rf /tmp/*
> 
> # Create the user
> RUN addgroup --gid $GROUP_ID user
> RUN useradd --create-home -s /bin/bash --uid $USER_ID --gid $GROUP_ID docker
> RUN adduser docker sudo
> RUN echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
> # USER docker
> 
> # Setup hierarchical_3d_gaussians
> RUN /opt/conda/bin/python -m ensurepip
> RUN /opt/conda/bin/python -m pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
> RUN /opt/conda/bin/python -m pip install plyfile tqdm joblib exif scikit-learn timm==0.4.5 opencv-python==4.9.0.80 gradio_imageslider gradio==4.29.0 matplotlib
> ```
> 
> but it keeps getting stuck here ![image](https://private-user-images.githubusercontent.com/49711774/351563561-4cf3c198-9578-4612-9ce7-5a0d85ed1a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDAyOTcsIm5iZiI6MTcyMTc5OTk5NywicGF0aCI6Ii80OTcxMTc3NC8zNTE1NjM1NjEtNGNmM2MxOTgtOTU3OC00NjEyLTljZTctNWEwZDg1ZWQxYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA1NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjQ2N2I1MWU0OTk3ZmFlYTQ4MjdiNDJmNGI2YmJiNjk3ODgxNDMxYzk5Njc0NjNlMjg2ZmQxNjM2OGMxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_7wlO7fsURcW2njBEveEQLNELRjCLMS7nHRIKOaXfY)

Well, same question, after about half an hour of waiting.

**Comment by Snosixtyboo** [comment]
@Linkersem 

Hi,
would you mind trying to make a new docker image, but with cuda 12.5.1?

**Comment by Linkersem** [comment]
hi, I'm sorry, but this is a bit difficult for me, mainly because these operations on the workstation, if i modify the graphics card driver and CUDA(max available version is 12.2), it may affect other people.

**Comment by Linkersem** [comment]
Hello, it doesn't seem to have to be run in a cuda 12.5 environment, I have a cuda 12.3 pytroch 2.3.0 device that works fine, hope that helps.

**Comment by SunHongyang10** [comment]
by far, cuda12.3 pytorch2.3.0 works

**Comment by kevintsq** [comment]
Currently CUDA 12.4 + PyTorch 2.4 works on Windows.

**Comment by ForeverAurorak** [comment]
Hi, I solved the problem.
The submodules/gaussianhierarchy/setup. py the "extra_compile_args" modified to
 {"cxx": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "dependencies/eigen/")]}.
The submodules/hierarchy-rasterizer/setup. py the "extra_compile_args" modified to
 {"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]}).
 Then reinstall the hierarchy-rasterizer "pip install submodules/hierarchy-rasterizer"
 Related issues:
          https://github.com/graphdeco-inria/gaussian-splatting/issues/41
          https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/10

**Comment by kevintsq** [comment]
Yes it works! Just a caveat, `-fno-gnu-unique` can only be used on Linux and `-Xcompiler` can only be passed to `nvcc`.

**Comment by GoroYeh-HRI** [comment]
I got the same error here (Ubuntu 18.04, nvcc -V 11.6)
I installed using  command:

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

![image](https://github.com/user-attachments/assets/83bacfda-0768-4b5e-b04c-dc6249b5d0f6)

After using @ForeverAurorak 's solution, it works and it's training now! Thank you so much!!!
![image](https://github.com/user-attachments/assets/8534f717-b71c-4436-a4b3-34ec39e01c5a)


> Hi, I solved the problem. The submodules/gaussianhierarchy/setup. py the "extra_compile_args" modified to {"cxx": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "dependencies/eigen/")]}. The submodules/hierarchy-rasterizer/setup. py the "extra_compile_args" modified to {"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "third_party/glm/")]}). Then reinstall the hierarchy-rasterizer "pip install submodules/hierarchy-rasterizer" Related issues: [graphdeco-inria/gaussian-splatting#41](https://github.com/graphdeco-inria/gaussian-splatting/issues/41) [graphdeco-inria/diff-gaussian-rasterization#10](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/10)

**Comment by rowellz** [comment]
Thank you to everyone in this thread for their awesome contributions, especially @ameuleman for providing a working Dockerfile. I was able to take it and put together a working docker-compose environment. Everything appears to be working but I still haven't figured out a way to connect to the remote viewer. If anyone is interested in running H3DGS via docker compose, here is the link to complete diff: [https://github.com/graphdeco-inria/hierarchical-3d-gaussians/pull/31/files](https://github.com/graphdeco-inria/hierarchical-3d-gaussians/pull/31/files) 

BTW I am running a RTX 3060 12GB with CUDA 12.3 installed on my host machine

**Comment by Gaaaavin** [comment]
> Hi, I solved the problem. The submodules/gaussianhierarchy/setup. py the "extra_compile_args" modified to {"cxx": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "dependencies/eigen/")]}. The submodules/hierarchy-rasterizer/setup. py the "extra_compile_args" modified to {"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "third_party/glm/")]}). Then reinstall the hierarchy-rasterizer "pip install submodules/hierarchy-rasterizer" Related issues: [graphdeco-inria/gaussian-splatting#41](https://github.com/graphdeco-inria/gaussian-splatting/issues/41) [graphdeco-inria/diff-gaussian-rasterization#10](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/10)

I think it should be `__file__` instead of `file` in the two lines.

> Yes it works! Just a caveat, `-fno-gnu-unique` can only be used on Linux and `-Xcompiler` can only be passed to `nvcc`.

This is a good point. In conclusion, the following code modification works for me on **Ubuntu**:
line 29 in `submodules/hierarchy-rasterizer/setup.py`:
```
extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]})
```
line 29 in `submodules/gaussianhierarchy/setup.py`:
```
extra_compile_args={"cxx": ["-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "dependencies/eigen/")]}
```

By modifying the two files above and reinstall via `pip install -r requirements.txt`, I got it to run smoothly.
I'm using a Ubuntu 20.04 machine, with PyTorch 2.3.0 (build for CUDA 12.1) and CUDA 12.1 runtime (`nvcc --version` = 12.1)
Note that this doesn't work if I'm using a CUDA 12.5 runtime as instructed above.

**Comment by alanvinx** [comment]
Hi thank you for your feedbacks, I pushed the fix to https://github.com/graphdeco-inria/hierarchy-rasterizer, please update your rasterizer using `git submodule update --remote`.

Regarding `gaussianhierarchy` I could run `full_train.py` successfully without modifying `submodules/gaussianhierarchy/setup.py` using the following Dockerfile with cuda 11.8 and 12.1.

> Hi, We are still working on a fix. In the meantime, I ran it without issue with Ubuntu 22.04 and CUDA 12.5. Here is the corresponding Dockerfile:
> 
> ```
> FROM nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04
> ARG USER_ID=1000
> ARG GROUP_ID=1000
> ENV DEBIAN_FRONTEND=noninteractive
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends git wget unzip bzip2 sudo build-essential ca-certificates openssh-server vim ffmpeg libsm6 libxext6 python3-opencv gcc-11 g++-11 cmake
> 
> # conda
> ENV PATH /opt/conda/bin:$PATH 
> RUN wget --quiet \
>     https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
>     echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
>     /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
>     rm -rf /tmp/*
> 
> # Create the user
> RUN addgroup --gid $GROUP_ID user
> RUN useradd --create-home -s /bin/bash --uid $USER_ID --gid $GROUP_ID docker
> RUN adduser docker sudo
> RUN echo "docker ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
> USER docker
> 
> # Setup hierarchical_3d_gaussians
> RUN /opt/conda/bin/python -m ensurepip
> RUN /opt/conda/bin/python -m pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
> RUN /opt/conda/bin/python -m pip install plyfile tqdm joblib exif scikit-learn timm==0.4.5 opencv-python==4.9.0.80 gradio_imageslider gradio==4.29.0 matplotlib
> ```
> 
> With 125.Dockerfile in `hierarchical-3d-gaussians/`:
> 
> ```
> DATASET_DIR=<Path to dataset>
> docker build -t hierarchical_3d_gaussians125 -f 125.Dockerfile .
> docker run -it --gpus=all --rm -v ${PWD}:/host -v ${DATASET_DIR}:/data --network=host --ipc=host hierarchical_3d_gaussians125 /bin/sh -c "cd /host; bash"
> rm -r submodules/hierarchy-rasterizer/build submodules/simple-knn/build submodules/gaussianhierarchy/build
> cd submodules/gaussianhierarchy
> cmake . -B build -DCMAKE_BUILD_TYPE=Release
> cmake --build build -j --config Release
> cd ../..
> /opt/conda/bin/python scripts/full_train.py --project_dir /data
> ```

**Comment by haofengsiji** [comment]
> > Hi, I solved the problem. The submodules/gaussianhierarchy/setup. py the "extra_compile_args" modified to {"cxx": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "dependencies/eigen/")]}. The submodules/hierarchy-rasterizer/setup. py the "extra_compile_args" modified to {"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "third_party/glm/")]}). Then reinstall the hierarchy-rasterizer "pip install submodules/hierarchy-rasterizer" Related issues: [graphdeco-inria/gaussian-splatting#41](https://github.com/graphdeco-inria/gaussian-splatting/issues/41) [graphdeco-inria/diff-gaussian-rasterization#10](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/10)
> 
> I think it should be `__file__` instead of `file` in the two lines.
> 
> > Yes it works! Just a caveat, `-fno-gnu-unique` can only be used on Linux and `-Xcompiler` can only be passed to `nvcc`.
> 
> This is a good point. In conclusion, the following code modification works for me on **Ubuntu**: line 29 in `submodules/hierarchy-rasterizer/setup.py`:
> 
> ```
> extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]})
> ```
> 
> line 29 in `submodules/gaussianhierarchy/setup.py`:
> 
> ```
> extra_compile_args={"cxx": ["-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "dependencies/eigen/")]}
> ```
> 
> By modifying the two files above and reinstall via `pip install -r requirements.txt`, I got it to run smoothly. I'm using a Ubuntu 20.04 machine, with PyTorch 2.3.0 (build for CUDA 12.1) and CUDA 12.1 runtime (`nvcc --version` = 12.1) Note that this doesn't work if I'm using a CUDA 12.5 runtime as instructed above.

fix my promblem, thanks !!!

**Comment by alancneves** [comment]
> > Hi, I solved the problem. The submodules/gaussianhierarchy/setup. py the "extra_compile_args" modified to {"cxx": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "dependencies/eigen/")]}. The submodules/hierarchy-rasterizer/setup. py the "extra_compile_args" modified to {"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(**file**)), "third_party/glm/")]}). Then reinstall the hierarchy-rasterizer "pip install submodules/hierarchy-rasterizer" Related issues: [graphdeco-inria/gaussian-splatting#41](https://github.com/graphdeco-inria/gaussian-splatting/issues/41) [graphdeco-inria/diff-gaussian-rasterization#10](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/10)
> 
> I think it should be `__file__` instead of `file` in the two lines.
> 
> > Yes it works! Just a caveat, `-fno-gnu-unique` can only be used on Linux and `-Xcompiler` can only be passed to `nvcc`.
> 
> This is a good point. In conclusion, the following code modification works for me on **Ubuntu**: line 29 in `submodules/hierarchy-rasterizer/setup.py`:
> 
> ```
> extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]})
> ```
> 
> line 29 in `submodules/gaussianhierarchy/setup.py`:
> 
> ```
> extra_compile_args={"cxx": ["-fno-gnu-unique","-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "dependencies/eigen/")]}
> ```
> 
> By modifying the two files above and reinstall via `pip install -r requirements.txt`, I got it to run smoothly. I'm using a Ubuntu 20.04 machine, with PyTorch 2.3.0 (build for CUDA 12.1) and CUDA 12.1 runtime (`nvcc --version` = 12.1) Note that this doesn't work if I'm using a CUDA 12.5 runtime as instructed above.

Fixed my problem on Ubuntu 22.04 + CUDA 11.8 + PyTorch 2.3.0 on docker!
