### ISSUE TITLE
cuda error about campus dataset inference

### ISSUE THREAD

**Issue by Radioheading** [graphdeco-inria/hierarchical-3d-gaussians#107]
When running the inference for the campus dataset, an error called "RuntimeError: CUDA error: device-side assert triggered" occurred.

To be specific, in line 225 of gaussian_renderer>init.py:
```
means3D = torch.cat((means3D_base, means3D[skybox_inds])).contiguous()
```
the index of skybox_inds is greater than the range of means3D

I wonder if this is the intrinsic problem of the dataset. Thank you very much!

**Comment by trinks-slam818** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the code to handle cases where skybox indices might be out of range for the means3D tensor. Add a check to ensure skybox_inds are within the valid range before concatenating.

You can review changes in this commit: https://github.com/trinks-slam818/graphdeco-inria-hierarchical-3d-gaussians-107/commit/c72f2e6dd771e3bd6fa03a4753c5024a25936049.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Radioheading** [comment]
Fine the problem is solved by manually excluding all the indices that exceed the bound
