### ISSUE TITLE
OOM ERROR

### ISSUE THREAD

**Issue by rab306** [graphdeco-inria/hierarchical-3d-gaussians#121]
I have tested the code about two months ago on my dataset and the method works smoothly but I'm trying to use it now and it keeps giving me OOM errors, I changed nothing, the same dataset, depth maps and even the same configurations, everything as you defined 
```
!python train_coarse.py -s /content/hierarchical-3d-gaussians/data/camera_calibration/aligned \
-i /content/hierarchical-3d-gaussians/data/camera_calibration/rectiifed/images \
--skybox_num 100000 \
--position_lr_init 0.00016 \
--position_lr_final 0.0000016 \
--save_iterations 10000 15000 \
--checkpoint_iterations 10000 15000 \
--model_path /content/hierarchical-3d-gaussians/data/output/scaffold 
```
and I keep getting this error 
```
Optimizing /content/hierarchical-3d-gaussians/data/output/scaffold
Output folder: /content/hierarchical-3d-gaussians/data/output/scaffold [27/02 22:53:39]
Reading camera 484/484 [27/02 22:53:41]
0 test images [27/02 22:53:41]
484 train images [27/02 22:53:41]
Making Training Dataset [27/02 22:53:41]
Making Test Dataset [27/02 22:53:41]
Number of points at initialisation :  474287 [27/02 22:53:41]
Training progress:   0% 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/hierarchical-3d-gaussians/train_coarse.py", line 190, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/content/hierarchical-3d-gaussians/train_coarse.py", line 94, in training
    render_pkg = render_coarse(viewpoint_cam, gaussians, pipe, background, indices = indices)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/hierarchical-3d-gaussians/gaussian_renderer/__init__.py", line 381, in render_coarse
    rendered_image, radii, _ = rasterizer(
                               ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/diff_gaussian_rasterization/__init__.py", line 205, in forward
    return rasterize_gaussians(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/diff_gaussian_rasterization/__init__.py", line 28, in rasterize_gaussians
    return _RasterizeGaussians.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/diff_gaussian_rasterization/__init__.py", line 84, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, invdepths = _C.rasterize_gaussians(*args)
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.77 GiB. GPU 
Training progress:   0% 0/30000 [00:00<?, ?it/s]
```
have you changed anything or am I doing something wrong?

**Comment by ameuleman** [comment]
Hi, 
It looks like it is related to https://github.com/graphdeco-inria/hierarchical-3d-gaussians/issues/4/. 
What is your GPU and CUDA version?

**Comment by rab306** [comment]
I'm using colab environment, CUDA version is 12.5 and I switch between A100 and L4

**Comment by rab306** [comment]
I get back to the repo and found CUDA 12.5 is supported so I used it with the pre-installed torch in colab environment instead of installing torch in the requirements and I did not get that error but instead I got this, the coarse training script script is stuck and there is no progress, it also consumes only 0.7 GB from the GPU. 
my images resolution is 2073x1369 and the size is 0.5 MB 

![Image](https://github.com/user-attachments/assets/20e39190-4440-48be-b653-43d04d6f89f0)

**Comment by rab306** [comment]
I have changed the cuda version to 12.1 and it works, I think there is a problem in 12.5 version
