### ISSUE TITLE
An error  occurs when train_single on my own data!

### ISSUE THREAD

**Issue by huster-wugj** [graphdeco-inria/hierarchical-3d-gaussians#6]
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%| | 90/30000 [00:12<1:11:24,  6.98it/s, Loss=0.0013641, D
Error executing train_single: Command 'python -u train_single.py --save_iterations -1 -i ../../rectified/images -d ../../rectified/depths --scaffold_file ./data/drive/output/scaffold/point_cloud/iteration_30000 --skybox_locked --alpha_masks ../../rectified/masks -s ./data/drive/camera_calibration/chunks/0_0 --model_path ./data/drive/output/trained_chunks/0_0 --bounds_file ./data/drive/camera_calibration/chunks/0_0' returned non-zero exit status 1.

**Comment by Snosixtyboo** [comment]
Hi, can you tell us about your setup? Are you using Docker?

**Comment by huster-wugj** [comment]
> Hi, can you tell us about your setup? Are you using Docker?

I . Not a docker.

> Hi, can you tell us about your setup? Are you using Docker?

Thank you for your reply. I have tried two configurations, cuda11.8 with torch2.3.1 and  cuda11.8 with torch2.1.2. Tested on A100 and Nvidia 3060. Now I am trying a docker cuda12.5.1 with torch2.3.1.

**Comment by White-Mask-230** [comment]
Try using the version 1.9.0 of torch.

Reference: https://github.com/pytorch/pytorch/issues/21819#issuecomment-1442643542

**Comment by Snosixtyboo** [comment]
> Try using the version 1.9.0 of torch.
> 
> Reference: [pytorch/pytorch#21819 (comment)](https://github.com/pytorch/pytorch/issues/21819#issuecomment-1442643542)

Pretty sure downgrading that much should not be nevessary. We are investigating issues with CUB, we will post updated when we know more

**Comment by huster-wugj** [comment]
Looking forward to receiving your updates.

**Comment by White-Mask-230** [comment]
It looks like a compatible bug.

The error appears in this configuration:

```
OS:     AWS sagemaker ml.g4dn.xlarge
GPU:    tesla t4
CUDA:   11.8.0
PYTORCH: 
	torch==2.0.0
	torchvision==0.15.1
IMAGE:  nvidia/cuda:11.8.0-base-ubuntu20.04
```

and it was solved by changing to this configuration:

```
OS:      AWS sagemaker ml.g4dn.xlarge
GPU:     tesla t4
CUDA:    11.3.1
PYTORCH: 
	 torch==1.12.1+cu113
	 torchvision==0.13.1+cu113
IMAGE:   nvidia/cuda:11.3.1-runtime-ubuntu20.04
```

Reference: [https://github.com/pytorch/pytorch/issues/21819#issuecomment-1641951847](https://github.com/pytorch/pytorch/issues/21819#issuecomment-1641951847)

**Comment by paujar** [comment]
Need to test this nextweek, I had also cuda 11.8

**Comment by Mrkomiljon** [comment]
is there tutorial to install this repo?
